basePath: /
definitions:
  schema.Event:
    properties:
      end_time:
        type: string
      id:
        type: integer
      start_time:
        type: string
      title:
        type: string
    type: object
  schema.EventPair:
    properties:
      end_time1:
        type: string
      end_time2:
        type: string
      id1:
        type: integer
      id2:
        type: integer
      start_time1:
        type: string
      start_time2:
        type: string
      title1:
        type: string
      title2:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This API is a test for Blankfactor
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Blankfactor Test API
  version: "1.0"
paths:
  /event:
    post:
      consumes:
      - application/json
      parameters:
      - description: event
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/schema.Event'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      tags:
      - event
    put:
      consumes:
      - application/json
      parameters:
      - description: event
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/schema.Event'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.Event'
      tags:
      - event
  /event/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      tags:
      - event
    get:
      consumes:
      - application/json
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.Event'
      tags:
      - event
  /event/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schema.Event'
            type: array
      tags:
      - event
  /event/list-overlap-pairs:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schema.EventPair'
            type: array
      tags:
      - event
swagger: "2.0"
